# -*- coding: utf-8 -*-
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
#The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
#However, their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
#difference are pentagonal and 
#D = |Pk − Pj| is minimised; what is the value of D?

def checkpent(x):
    z = ((24*x+1)**0.5+1)/6
    return z


for i in xrange(1,10000):
    for j in xrange(i+1,10000):
        ipen = i*(3*i-1)/2
        jpen = j*(3*j-1)/2
        ijsum = ipen + jpen
        ijdiff = jpen-ipen
        x = checkpent(ijsum)
        y=checkpent(ijdiff)
        if x.is_integer():
            if y.is_integer():
                print ipen, jpen,ijdiff
                
                
